### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by scf37** [kostaskougios/scalascriptengine#17]
I was looking for compilation library to support hot reloading of individual classes - it is faster than sbt watch.

**Comment by kostaskougios** [comment]
I will try to build the lib for 2.12

**Comment by Proximator** [comment]
Any update on this issue?

**Comment by scf37** [comment]
Here is the code I borrowed from this library and changed here and there for my needs. And Scala 2.12.

https://gist.github.com/scf37/3aefc73ed44fde338e7f7ad813a2ad6f

**Comment by kostaskougios** [comment]
Hi all, the code needs several changes to be updated to scala 2.12. I am looking into it.

**Comment by kostaskougios** [comment]
I've updated scalascriptengine to use scala 2.12. There is a non-issue on 1 testcase that occurs when tests run all together and I also need to upload the artifacts, which I will do at some time later on. But you can build the artifacts locally by checking out branch "2.12"

**Comment by kostaskougios** [comment]
..and published 1.3.11 snapshots for scala 2.12 in maven central: https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/scalascriptengine/scalascriptengine_2.12/1.3.11-SNAPSHOT/

**Comment by kostaskougios** [comment]
Ok pushed artifact 1.3.11 for scala 2.12.
